resolver: lts-18.19
# resolver: lts-14.1
packages:
- .
extra-deps:
  # jsem
  - git: http://github.com/DaisukeBekki/JSeM
    commit: c2cd39168e267007b4690dbf625329bac57a8185

  # nlp-tools
  - git: http://github.com/DaisukeBekki/nlp-tools
    commit: e4bd3783f4e872b8df29538d9219e41f40378363

  # lightblue
  - git: https://github.com/kohapizza/lightblue.git
    commit: 4fe2da3b3cfc2b534b3dd343806f741fa78395c6

  - classy-prelude-yesod-1.5.0@sha256:8f7e183bdfd6d2ea9674284c4f285294ab086aff60d9be4e5d7d2f3c1a2b05b7,1330
flags: {}
extra-package-dbs: []
